### ISSUE TITLE
Assignment 5

### ISSUE THREAD

**Issue by oyamad** [R-Tsushima/linear-interpolation.jl#5]
[課題5](https://github.com/OyamaZemi/exercises2016/tree/master/ex05)をがんばってやってみましょう．わからないことがあればここに書いてください．

**Comment by R-Tsushima** [comment]
MethodErrorが出てしまいます
no method matching bellman_operator(::LinSpace{Float64}, ::Array{Float64,1})
Closest candidates are:
  bellman_operator(!Matched::GrowthModel, ::Array{T,1}; ret_policy) at In[2]:112
while loading In[3], in expression starting on line 1

 in main(::Int64) at .\In[2]:155
 in main() at .\In[2]:149

**Comment by oyamad** [comment]
エラーが出るコードはどこにありますか．

**Comment by R-Tsushima** [comment]
すみません。今、僕のlinear-interpolation.jlのレポジトリに上げました
A Simple Optimal Growth Model Interpolation2 です

**Comment by oyamad** [comment]
どうですか．できましたか．

**Comment by R-Tsushima** [comment]
- のメソッドエラーが出てしまいます

**Comment by oyamad** [comment]
`x < grid[1]` や `x > grid[end]` のときも値を返したらどうなりますか．

**Comment by oyamad** [comment]
コピペ元にあるとおり `Plots` を使うようにしたらどうなりますか．

**Comment by R-Tsushima** [comment]
描けました

**Comment by oyamad** [comment]
OyamaZemi/exercises2016#46 にしたがってプルリクエストだしてください．

**Comment by R-Tsushima** [comment]
SourceTreeでexercises2016のレポジトリーをマージするところでエラーが発生してしまいます
これは僕のアカウント内でのレポジトリーに変更を加えてしまってるということですか？

git -c diff.mnemonicprefix=false -c core.quotepath=false merge upstream/master
Auto-merging ex02/notebooks.md
CONFLICT (content): Merge conflict in ex02/notebooks.md
Automatic merge failed; fix conflicts and then commit the result.

**Comment by oyamad** [comment]
どういう操作をしてそのエラーが出たのかわかりませんが，次のようにやったらどうなりますか．
- SourceTree の「リモート」の「origin」(があれば) を開いて「master」をダブルクリック．
- 「新規ローカルブランチ名」が `master` のままでうまくいかなければ，別の適切な名前をつけてみる．
- それでうまくいけば，`ex05/notebooks.md` を編集して，コミットしてプッシュする．

**Comment by oyamad** [comment]
どうですか．できましたか．

**Comment by R-Tsushima** [comment]
うまくいかないです。
見てもらってもいいですか。

**Comment by oyamad** [comment]
@myuuuuun @nswa17 コンピュータルームにいるのなら見てあげてもらえませんか．

**Comment by a-matsushita** [comment]
https://github.com/OyamaZemi/exercises2016/blob/master/ex05/notebooks.md を直接github上で編集すればいいと思いますが, うまくいかないですか

**Comment by a-matsushita** [comment]
おそらく自分のレポジトリにあるex02のnotebook.mdを編集したのだと思いますが, 
- もしフォークした自分のレポジトリから親のリポジトリにPRを出したいのであれば, 自分のリポジトリを親の最新の状態に合わせる（or conflictを手で解決する）ことをした上で, ex05のnotebook.mdを編集する
- あるいは, 直接親のgithub上のファイルを編集して, PRを出す

のいずれかをする必要があると思います.
